<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "completing".
 * 
 * @property int $id
 * @property int|null $user_id
 * @property string|null $video_first
 * @property string|null $video_second
 * @property string|null $video_third
 * @property string|null $video_fourth
 * @property string|null $video_fifth
 * @property string|null $video_sixth
 * @property string|null $video_seventh
 * @property string|null $video_eighth
 * @property string|null $video_ninth
 * @property string|null $video_tenth
 * @property string|null $video_number
 */
class Completing extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'completing';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'integer'],
            [['video_first', 'video_second', 'video_third', 'video_fourth', 'video_fifth', 'video_sixth', 'video_seventh', 'video_eighth', 'video_ninth', 'video_tenth'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'video_first' => 'Video First',
            'video_second' => 'Video Second',
            'video_third' => 'Video Third',
            'video_fourth' => 'Video Fourth',
            'video_fifth' => 'Video Fifth',
            'video_sixth' => 'Video Sixth',
            'video_seventh' => 'Video Seventh',
            'video_eighth' => 'Video Eighth',
            'video_ninth' => 'Video Ninth',
            'video_tenth' => 'Video Tenth',
        ];
    }

    public function saveImage($filename, $numberTask)
    {
        $this->$numberTask = $filename;
        return $this->save(false);
    }
    
    public function getImageOne()
    {
        return ($this->video_first) ? '/uploads/' . $this->video_first : 'd9f16c0ddb1b43b738f13ade8ff03d2e.mp4';
    }
    public function getImageTwo()
    {
        return ($this->video_second) ? '/uploads/' . $this->video_second : '/no-image.png';
    }
    public function getImageThree()
    {
        return ($this->video_third) ? '/uploads/' . $this->video_third : '/no-video.mp4';
    }
    public function getImageFour()
    {
        return ($this->video_fourth) ? '/uploads/' . $this->video_fourth : '/no-image.png';
    }
    public function getImageFive()
    {
        return ($this->video_fifth) ? '/uploads/' . $this->video_fifth : '/no-image.png';           
    }
    public function getImageSix()
    {
        return ($this->video_sixth) ? '/uploads/' . $this->video_sixth : '/no-image.png';
    }
    public function getImageSeven()
    {
        return ($this->video_seventh) ? '/uploads/' . $this->video_seventh : '/no-image.png';
    }
    public function getImageEight()
    {
        return ($this->video_eighth) ? '/uploads/' . $this->video_eighth : '/no-image.png';
    }
    public function getImageNine()
    {
        return ($this->video_ninth) ? '/uploads/' . $this->video_ninth : '/no-image.png';
    }
    public function getImageTen()
    {
        return ($this->video_tenth) ? '/uploads/' . $this->video_tenth : '/no-image.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new UploadImage();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
