<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tape".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $video
 * @property string|null $date
 * @property string|null $dates
 * @property string|null $name_player
 * @property string|null $tape_task
 */
class Tape extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tape';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'integer'],
            [['date', 'dates'], 'safe'],
            [['video'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'video' => 'Video',
            'date' => 'Date',
            'dates' => 'Dates',
        ];
    }

    public function saveImage($filename, $video, $userId, $player, $numberTask)
    {
        $this->$video = $filename;
        $this->user_id = $userId;
        $this->name_player = $player->name;
        $this->tape_task = $numberTask;
        return $this->save(false);
    }
    
    public function getImage()
    {
        return ($this->video) ? '/uploads/' . $this->video : 'd9f16c0ddb1b43b738f13ade8ff03d2e.mp4';
    }

    public function deleteImage()
    {
        $imageUploadModel = new UploadImage();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }

}
