<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "task".
 *
 * @property int $id
 * @property string|null $task_name
 * @property string|null $description
 * @property string|null $completion_date
 * @property string|null $completion_time
 * @property string|null $image
 * @property string|null $video
 * @property int|null $viewed
 * @property int|null $user_id
 * @property int|null $status
 * @property int|null $price
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['completion_date', 'completion_time'], 'safe'],
            [['viewed', 'user_id', 'status', 'price'], 'integer'],
            [['task_name', 'image', 'video'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'task_name' => 'Task Name',
            'description' => 'Description',
            'completion_date' => 'Completion Date',
            'completion_time' => 'Completion Time',
            'image' => 'Image',
            'video' => 'Video',
            'viewed' => 'Viewed',
            'user_id' => 'User ID',
            'status' => 'Status',
            'price' => 'Price',
        ];
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }
    public function getImage()
    {
        return ($this->image) ? '/uploads/' . $this->image : '/no-image.png';
    }

    public function deleteImage()
    {
        $imageUploadModel = new UploadImage();
        $imageUploadModel->deleteCurrentImage($this->image);
    }

    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
